services:
  neo4j:
    image: docker.io/neo4j:5.15-community
    container_name: logistics_neo4j
    hostname: logistics_neo4j
    ports:
      - "7474:7474" # HTTP (Browser)
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password123
      # IMPORTANTE: Forzamos la descarga limpia de los plugins
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_apoc_export_file_enabled=true
    volumes:
      - neo4j_data:/data:Z
      - neo4j_logs:/logs:Z
      # MAPEADO A CARPETA LOCAL: Para limpiar archivos corruptos fácilmente
      - ./plugins:/plugins:Z

volumes:
  neo4j_data:
  neo4j_logs:
